workflows:
  build-all:
    name: Build Android Signed + iOS Unsigned
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - android-signing

    scripts:
      # Decode keystore dari BASE64 ke file .jks
      - name: Decode keystore (Base64 → .jks)
        script: |
          echo "$ANDROID_KEYSTORE" | base64 --decode > android/app/key.jks

      # Install dependency Flutter
      - name: Install dependencies
        script: |
          flutter pub get

      # -----------------------
      # ANDROID SIGNED BUILDS
      # -----------------------
      - name: Set up Android signing
        script: |
          echo "storePassword=$ANDROID_KEYSTORE_PASSWORD" > android/key.properties
          echo "keyPassword=$ANDROID_KEY_PASSWORD" >> android/key.properties
          echo "keyAlias=$ANDROID_KEY_ALIAS" >> android/key.properties
          echo "storeFile=key.jks" >> android/key.properties

      - name: Build Android APK
        script: |
          flutter build apk --release

      - name: Build Android AAB
        script: |
          flutter build appbundle --release

      # -----------------------
      # IOS UNSIGNED BUILD
      # -----------------------
      - name: Build iOS (Unsigned)
        script: |
          flutter build ios --release --no-codesign

      - name: Package unsigned IPA
        script: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r Runner-unsigned.ipa Payload

    artifacts:
      # Android signed
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab

      # iOS unsigned
      - build/ios/iphoneos/Runner.app
      - build/ios/iphoneos/Payload
      - build/ios/iphoneos/Runner-unsigned.ipa

    publishing:
      email:
        recipients:
          - hasanmahfudh112@gmail.com
